version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - echo "Navigating to the correct directory..."
      - cd securityApp  # Change directory to where pom.xml is located
      - ls -la  # Debugging: Check if pom.xml exists
      - mvn clean package -DskipTests
  post_build:
    commands:
      - echo "Build, Testing, and Packaging completed."

artifacts:
  files:
    - securityApp/target/*.jar  # Update to match your actual JAR path
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'
