version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - echo Building, Testing and packaging the application...
      - mvn package -DskipTests || { echo "Maven build failed!"; exit 1; }
      - ls -R target/  # List files in target directory
  post_build:
    commands:
      - echo Build, Testing and packaging completed.
artifacts:
  files:
    - target/*.jar
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'